#! /bin/sh
# /etc/init.d/blah
#


# Carry out specific functions when asked to by the system
case "$1" in
  start)
    export COUNTRY=00; crda
    iw reg set US
    ifconfig wlan1 up 10.0.0.1 netmask 255.255.255.0
    service isc-dhcp-server restart
    cd /home/
    hostapd hostapd5Ghz.conf -B
    cd /home/sender/
    ./sender & 
    ;;
esac

exit 0
